# Generated by Django 5.1 on 2024-08-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='termos',
        ),
    
       
    ]
