# Generated by Django 5.1 on 2024-08-20 11:08

from django.db import migrations, models

def create_default_levels(apps, schema_editor):
    Nivel = apps.get_model('jback', 'Nivel')
    defaults = [
        'iniciante',
        'habilitado',
        'especialista',
    ]
    for descricao in defaults:
        Nivel.objects.get_or_create(descricao=descricao)

def create_default_access_types(apps, schema_editor):
    TipoAcesso = apps.get_model('jback', 'TipoAcesso')
    defaults = [
        'master',
        'comum',
        'técnico',
    ]
    for descricao in defaults:
        TipoAcesso.objects.get_or_create(descricao=descricao)

class Migration(migrations.Migration):

    dependencies = [
        ('jback', '0002_remove_tecnico_termos'),  # Certifique-se de que esta dependência está correta.
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='termos',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_default_levels),
        migrations.RunPython(create_default_access_types),
    ]