# Generated by Django 5.1 on 2024-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jback', '0003_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
