# Generated by Django 5.1 on 2024-09-06 16:23

from django.db import migrations, models

def criar_tipos_servico(apps, schema_editor):
    TipoServico = apps.get_model('jback', 'TipoServico')
    tipos = [
        'Vistoria', 'Assistência', 'Desmontagem', 'Desinstalação', 'Montagem',
        'Retirada de produto (Loja)', 'Retirada de produto (Cliente)', 'Entrega',
        'Ripado acabado', 'Ripado s/ acabamento', 'Medição planejado', 
        'Medição IS7', 'Fabricação', 'Serviço em loja'
    ]

    for tipo in tipos:
        TipoServico.objects.create(descricao=tipo)

class Migration(migrations.Migration):

    dependencies = [
        ('jback', '0003_tecnico_termos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(criar_tipos_servico),
    ]
