# Generated by Django 5.1 on 2024-08-19 17:50

import django.db.models.deletion
from django.db import migrations, models


def create_default_levels(apps, schema_editor):
    Nivel = apps.get_model('jback', 'Nivel')
    Nivel.objects.bulk_create([
        Nivel(descricao='iniciante'),
        Nivel(descricao='habilitado'),
        Nivel(descricao='especialista'),
    ])

def create_default_access_types(apps, schema_editor):
    TipoAcesso = apps.get_model('jback', 'TipoAcesso')
    TipoAcesso.objects.bulk_create([
        TipoAcesso(descricao='master'),
        TipoAcesso(descricao='comum'),
        TipoAcesso(descricao='técnico'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('jback', '0004_alter_loja_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('habilitado', models.BooleanField(default=True)),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jback.nivel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jback.tipoacesso'),
        ),
        migrations.RunPython(create_default_levels),
        migrations.RunPython(create_default_access_types),
    ]
