# Generated by Django 5.1 on 2024-09-25 12:13

from django.db import migrations


def create_tipo_regime(apps, schema_editor):
    TipoRegime = apps.get_model('jcont', 'TipoRegime')  # Substitua <app_name> pelo nome do seu app
    regimes = [
        "LUCRO PRESUMIDO",
        "LUCRO REAL",
        "SIMPLES NACIONAL"
    ]

    for regime in regimes:
        TipoRegime.objects.get_or_create(descricao=regime)
 
        
class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0002_tiporegime'),
    ]

    operations = [
        migrations.RunPython(create_tipo_regime),
    ]
