# Generated by Django 5.1 on 2024-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0003_auto_20240925_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
