# Generated by Django 5.1 on 2024-09-25 12:22

from django.db import migrations

def create_ramo_atividade(apps, schema_editor):
    RamoAtividade = apps.get_model('jcont', 'RamoAtividade')  # Substitua <app_name> pelo nome do seu app
    atividades = [
        "INDUSTRIA",
        "COMERCIO",
        "SERVIÇO"
    ]

    for atividade in atividades:
        RamoAtividade.objects.get_or_create(descricao=atividade)      

class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0004_ramoatividade'),
    ]

    operations = [
        migrations.RunPython(create_ramo_atividade),
    ]
