# Generated by Django 5.1 on 2024-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0005_auto_20240925_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('cod_setor', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_setor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
