# Generated by Django 5.1 on 2024-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0006_cnae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('apelido_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('regime_tributario', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('ramo_atividade', models.CharField(max_length=255)),
                ('cnae_principal', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cnae',
            name='cod_setor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cnae',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cnae',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
