# Generated by Django 5.1 on 2024-09-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0007_cliente_alter_cnae_cod_setor_alter_cnae_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnae_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jcont.cnae'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ramo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jcont.ramoatividade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regime_tributario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jcont.tiporegime'),
        ),
    ]
