# Generated by Django 5.1 on 2024-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0008_alter_cliente_cnae_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop', models.CharField(max_length=20)),
                ('cod_prod', models.CharField(max_length=50)),
                ('ncm', models.CharField(max_length=20)),
                ('descricao_cliente', models.CharField(max_length=255)),
                ('descricao_banco', models.CharField(max_length=255)),
                ('cst_icms', models.CharField(max_length=10)),
                ('cst_pis', models.CharField(max_length=10)),
                ('cst_cofins', models.CharField(max_length=10)),
                ('reducao', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DadosReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=20, unique=True)),
                ('cst_icms', models.CharField(max_length=10)),
                ('cst_pis', models.CharField(max_length=10)),
                ('cst_cofins', models.CharField(max_length=10)),
                ('reducao', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
