# Generated by Django 5.1 on 2024-09-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0009_clienteexcel_dadosreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteexcel',
            name='cfop',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clienteexcel',
            name='cod_prod',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clienteexcel',
            name='ncm',
            field=models.CharField(max_length=100),
        ),
    ]
