# Generated by Django 5.1 on 2024-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0010_alter_clienteexcel_cfop_alter_clienteexcel_cod_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteexcel',
            name='id_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
