# Generated by Django 5.1 on 2024-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0011_clienteexcel_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosreferencia',
            name='ncm',
            field=models.CharField(max_length=20),
        ),
    ]
