# Generated by Django 5.1 on 2024-09-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0012_alter_dadosreferencia_ncm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteexcel',
            name='descricao_cliente',
        ),
        migrations.RemoveField(
            model_name='clienteexcel',
            name='reducao',
        ),
        migrations.AlterField(
            model_name='clienteexcel',
            name='cfop',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
