# Generated by Django 5.1 on 2024-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0013_remove_clienteexcel_descricao_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosreferencia',
            old_name='cst_icms',
            new_name='codigo_original_tipi',
        ),
        migrations.RemoveField(
            model_name='dadosreferencia',
            name='ncm',
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='codigo_sem_ponto',
            field=models.CharField(default='NT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='cst_icms_es',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='cst_icms_mg',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='cst_icms_rj',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='cst_icms_sp',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='descricao_tipi',
            field=models.CharField(default='NT', max_length=255),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='etc',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='ipi',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AddField(
            model_name='dadosreferencia',
            name='tipo',
            field=models.CharField(default='NT', max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_cofins',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_pis',
            field=models.CharField(default='NT', max_length=4),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='reducao',
            field=models.DecimalField(decimal_places=2, default='NT', max_digits=5),
        ),
    ]
