# Generated by Django 5.1 on 2024-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0014_rename_cst_icms_dadosreferencia_codigo_original_tipi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosreferencia',
            name='reducao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
