# Generated by Django 5.1 on 2024-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0015_alter_dadosreferencia_reducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_cofins',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_icms_es',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_icms_mg',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_icms_rj',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_icms_sp',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='cst_pis',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='etc',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='ipi',
            field=models.CharField(default='NT', max_length=9),
        ),
        migrations.AlterField(
            model_name='dadosreferencia',
            name='reducao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
