# Generated by Django 5.1 on 2024-11-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcont', '0016_alter_dadosreferencia_cst_cofins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosreferencia',
            name='etc',
        ),
    ]
